# Mirrors action/download-artifact, taking many of the same parameters, but download from S3 instead of GitHub.
# based on open-turo/actions-s3-artifact
# See: https://github.com/open-turo/actions-s3-artifact/blob/main/download/action.yaml
name: Download AWS S3 Artifact
description: Downloads an artifact from an AWS S3 bucket

# Inputs, outputs and descriptions pulled from actions/download-artifact
inputs:
  name:
    description: Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
    required: false
  path:
    description: Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
    required: false
  # TODO: implement pattern
  pattern:
    description: A glob pattern matching the artifacts that should be downloaded. Ignored if name is specified.
    required: false
  # TODO: implement merge-multiple
  merge-multiple:
    description: >
      When multiple artifacts are matched, this changes the behavior of the destination directories.
      If true, the downloaded artifacts will be in the same directory specified by path.
      If false, the downloaded artifacts will be extracted into individual named directories within the specified path.
      required: false
      default: false
  # TODO: implement repository
  repository:
    description: >
      The repository owner and the repository name joined together by "/".
      If github-token is specified, this is the repository that artifacts will be downloaded from.
      required: false
    default: github.repository
  # TODO: implement run-id
  run-id:
    description: >
      The id of the workflow run where the desired download artifact was uploaded from.
      If github-token is specified, this is the run that artifacts will be downloaded from.
      required: false
    default: github.run_id
outputs:
  download-path:
    description: Path of artifact download

runs:
  using: 'composite'
  steps:
    - name: Download artifact
      shell: bash
      run: |
        # read inputs
        scripts/read_inputs.sh

        # run script
        scripts/main.sh